<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\NewsUpgrade\Repository;

use Eccube\Entity\News;
use Eccube\Repository\AbstractRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\DBAL\Exception\DriverException;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Doctrine\Persistence\ManagerRegistry;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TintucRepository extends AbstractRepository {

    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, News::class);
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderPublished() {
        $qb = $this->createQueryBuilder('n');
        $qb->setParameter('now', new \DateTime('now'))
                ->where('n.publish_date <= :now')
                ->andWhere('n.visible = true')
                ->addOrderBy('n.publish_date', 'DESC')
                ->addOrderBy('n.id', 'DESC');

        return $qb;
    }

}
